# This file exists so users can easily get started with ffsim
# in a container using Docker Compose.

services:
  notebook:
    build: .
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - 8888:8888
    volumes:
      - ffsim:/home/jovyan/persistent-volume

volumes:
  ffsim: