# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

"""Generate API docs for the ffsim package.

Run this script after adding or removing symbols from the ffsim package:

    python docs/generate_api_docs.py

This generates:
- docs/api/ffsim.rst from python/ffsim/__init__.py
- docs/api/ffsim.<submodule>.rst for each public submodule

The section headings in ffsim.rst are read from the first line of each
submodule's docstring, and the remainder of the docstring is included as a
paragraph. To change a heading or description, edit the corresponding module
docstring and re-run this script.
"""

import ast
import pkgutil
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
INIT_FILE = REPO_ROOT / "python" / "ffsim" / "__init__.py"
OUTPUT_FILE = REPO_ROOT / "docs" / "api" / "ffsim.rst"
INDEX_FILE = REPO_ROOT / "docs" / "api" / "index.md"
FFSIM_PKG = REPO_ROOT / "python" / "ffsim"
DOCS_API_DIR = REPO_ROOT / "docs" / "api"


def get_module_docstring(submodule: str) -> tuple[str, str]:
    """Return (heading, body) from a submodule's docstring.

    heading is the first line with trailing period stripped.
    body is the remainder of the docstring after the first line (stripped).
    """
    pkg_path = FFSIM_PKG / submodule / "__init__.py"
    mod_path = FFSIM_PKG / f"{submodule}.py"
    if pkg_path.exists():
        path = pkg_path
    elif mod_path.exists():
        path = mod_path
    else:
        raise FileNotFoundError(f"Cannot find module file for ffsim.{submodule}")
    tree = ast.parse(path.read_text())
    docstring = ast.get_docstring(tree)
    if not docstring:
        raise ValueError(f"Module ffsim.{submodule} has no docstring")
    lines = docstring.splitlines()
    heading = lines[0].rstrip(".")
    body = "\n".join(lines[1:]).strip()
    return heading, body


def autosummary_section(heading: str, body: str, symbols: list[str]) -> str:
    underline = "-" * len(heading)
    entries = "\n".join(f"   {sym}" for sym in symbols)
    paragraph = f"\n{body}\n" if body else ""
    return f"{heading}\n{underline}\n{paragraph}\n.. autosummary::\n   :toctree: stubs/\n\n{entries}\n"  # noqa: E501


def generate_submodule_rst(submodule: str) -> None:
    """Generate docs/api/ffsim.<submodule>.rst."""
    pkg_path = FFSIM_PKG / submodule / "__init__.py"
    mod_path = FFSIM_PKG / f"{submodule}.py"
    if pkg_path.exists():
        path = pkg_path
    elif mod_path.exists():
        path = mod_path
    else:
        raise FileNotFoundError(f"Cannot find module file for ffsim.{submodule}")

    tree = ast.parse(path.read_text())

    # Read __all__ for the canonical symbol list.
    symbols: list[str] = []
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id == "__all__":
                if isinstance(node.value, (ast.List, ast.Tuple)):
                    symbols = [
                        elt.value
                        for elt in node.value.elts
                        if isinstance(elt, ast.Constant) and isinstance(elt.value, str)
                    ]

    title = f"ffsim.{submodule}"
    underline = "=" * len(title)
    entries = "\n".join(f"   {sym}" for sym in symbols)

    output_path = DOCS_API_DIR / f"ffsim.{submodule}.rst"
    output_path.write_text(
        f".. This file is auto-generated by docs/generate_api_docs.py.\n"
        f".. Do not edit it manually.\n"
        f"\n"
        f"{title}\n"
        f"{underline}\n"
        f"\n"
        f".. currentmodule:: ffsim.{submodule}\n"
        f"\n"
        f".. autosummary::\n"
        f"   :toctree: stubs/\n"
        f"\n"
        f"{entries}\n"
    )
    print(f"Written {output_path}")


def generate_index_md(submodules: list[str]) -> None:
    """Generate docs/api/index.md."""
    entries = "\n".join(f"ffsim.{sub}" for sub in submodules)
    INDEX_FILE.write_text(
        f"<!-- This file is auto-generated by docs/generate_api_docs.py. -->\n"
        f"<!-- Do not edit it manually. -->\n"
        f"\n"
        f"# API reference\n"
        f"\n"
        f"```{{toctree}}\n"
        f":maxdepth: 1\n"
        f"\n"
        f"ffsim\n"
        f"{entries}\n"
        f"```\n"
    )
    print(f"Written {INDEX_FILE}")


def main() -> None:
    tree = ast.parse(INIT_FILE.read_text())

    # Collect (submodule, symbols) groups in source order.
    # Only process "from ffsim.<submodule> import ..." nodes.
    sections: list[tuple[str, list[str]]] = []
    for node in tree.body:
        if not isinstance(node, ast.ImportFrom):
            continue
        module = node.module or ""
        if not module.startswith("ffsim."):
            continue
        submodule = module[len("ffsim.") :]
        symbols = [alias.name for alias in node.names]
        sections.append((submodule, symbols))

    # Detect separately-documented submodules: public submodules of the ffsim
    # package that are not re-exported in ffsim's __init__.py.
    merged = {submodule for submodule, _ in sections}
    submodules = sorted(
        mod.name
        for mod in pkgutil.iter_modules([str(FFSIM_PKG)])
        if not mod.name.startswith("_") and mod.name not in merged
    )

    lines: list[str] = [
        ".. This file is auto-generated by docs/generate_api_docs.py.\n",
        ".. Do not edit it manually. To update section headings, edit the\n",
        ".. corresponding module docstring and re-run the script.\n",
        "\n",
        "ffsim\n",
        "=====\n",
        "\n",
        ".. currentmodule:: ffsim\n",
    ]

    for submodule, symbols in sections:
        heading, body = get_module_docstring(submodule)
        lines.append("\n")
        lines.append(autosummary_section(heading, body, symbols))

    OUTPUT_FILE.write_text("".join(lines))
    print(f"Written {OUTPUT_FILE}")

    for submodule in submodules:
        generate_submodule_rst(submodule)

    generate_index_md(submodules)


if __name__ == "__main__":
    main()
