name: Build and deploy documentation

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          sudo apt update
          sudo apt install -y libopenblas-dev pandoc
      - name: Build docs
        run: |
          tox run -e docs
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html/
